export default [
  { title: 'React', link: 'https://reactjs.org/' },
  { title: 'TypeScript', link: 'https://www.typescriptlang.org/' },
  { title: 'Next.js', link: 'https://nextjs.org/' },
  { title: 'Zustand', link: 'https://zustand-demo.pmnd.rs/' },
  { title: 'TanStack', link: 'https://tanstack.com/' },
  { title: 'GraphQL', link: 'https://graphql.org/' },
  { title: 'tRPC', link: 'https://trpc.io/' },
  { title: 'Tailwind CSS', link: 'https://tailwindcss.com/' },
  { title: 'styled-components', link: 'https://styled-components.com/' },
  { title: 'Shadcn/ui', link: 'https://ui.shadcn.com/' },
  { title: 'React Hook Form', link: 'https://react-hook-form.com/' },
  { title: 'Zod', link: 'https://zod.dev/' },
  { title: 'Vite', link: 'https://vitejs.dev/' },
  { title: 'Turbopack', link: 'https://turbo.build/pack' },
  { title: 'Vitest', link: 'https://vitest.dev/' },
  { title: 'Playwright', link: 'https://playwright.dev/' },
  { title: 'Testing Library', link: 'https://testing-library.com/' },
  { title: 'Node.js', link: 'https://nodejs.org/' },
  { title: 'Bun', link: 'https://bun.sh/' },
  { title: 'Prisma', link: 'https://www.prisma.io/' },
  { title: 'PostgreSQL', link: 'https://www.postgresql.org/' },
  { title: 'Git', link: 'https://git-scm.com/' },
  { title: 'GitHub Actions', link: 'https://github.com/features/actions' },
  { title: 'Docker', link: 'https://www.docker.com/' },
  { title: 'Turborepo', link: 'https://turbo.build/repo' },
  { title: 'Vercel', link: 'https://vercel.com/' },
  { title: 'Figma', link: 'https://www.figma.com/' },
  { title: 'Biome', link: 'https://biomejs.dev/' },
]
