export default [
  {
    name: 'Beihang University',
    field: 'Economics & Management',
    year: '2016',
    logo: 'beihang-uni',
    courses: [
      'Applied Statistics',
      'Financial Management',
      'Statistics',
      'Chinese Culture',
      'Chinese Language',
    ],
  },
  {
    name: 'Gent Universiteit',
    field: 'Economics & Business Administration',
    year: '2013 - 2014',
    logo: 'ugent-uni',
    courses: [
      'Consumer Behaviour',
      'Marketing Communication',
      'Total Quality Management',
      'Applied Operational Research',
      'ICT Management',
      'Project Management',
      'Management Coontrol',
      'Dutch Language',
    ],
  },
  {
    name: 'Czech Technical University',
    field: 'Economics & Management  of Electrical Engineering',
    year: '2013 - 2016',
    logo: 'ctu-uni',
    courses: [
      'Supply Chain Management',
      'Accountancy',
      'Quality Management',
      'Statistical methods in Economy',
      'Financial Management',
      'Information System Engineering',
      'Ecology and Economy',
    ],
  },
  {
    name: 'Czech Technical University',
    field: 'Software Technology & Management',
    year: '2009 - 2013',
    logo: 'ctu-uni',
    courses: [
      'Corporate Performance Management',
      'Business Process Management',
      'Programming in Java',
      'Marketing',
      'Management in IT',
      'Design Patterns',
      'Analysis of Algorythms',
    ],
  },
] as const
