export default [
  {
    company: "Exaforce",
    date: "2024 - 2025 (contract)",
    position: "Senior Product Engineer",
    responsibilities: [
      "US-based AI-powered security startup (Series A, $75M raised)",
      "Built core analytics features. Worked directly with the CEO on what to ship next",
      "Tuned SQL on a custom data layer to keep dashboards fast at real-time scale",
      "Built customized frontend using Superset, React, TypeScript, Redux, Vite, TanStack Query/Table, Emotion CSS-in-JS",
      "Implemented YAML-driven dashboard creation system",
    ],
  },
  // {
  //   company: 'Vitus Labs',
  //   date: '2018 - 2025',
  //   position: 'Founding Creator & Engineer',
  //   responsibilities: [
  //     'Created open-source libraries for multiplatform UI design systems',
  //     'Developed tools that eliminate web/monorepo configuration overhead',
  //     'Helped teams build faster, more beautiful frontends with minimal setup',
  //     'Active contributor to the developer community',
  //   ],
  // },
  {
    company: "BOOTIQ",
    date: "2023 (contract)",
    position: "Tech Lead/Consultant",
    responsibilities: [
      "Partnered directly with clients on business-critical technical challenges",
      "Provided technical strategy and sales support for deal proposals",
      "Conducted deep technical analyses and architecture recommendations for 20+ client projects",
      "Designed scalable web application architectures and development workflows for starting projects",
      "Resolved critical production issues for client projects",
      "Evaluated team capabilities and defined growth strategies",
    ],
  },
  {
    company: "KINDRED.",
    date: "2021 - 2022 (contract)",
    position: "Engineering Team/Tech Lead",
    responsibilities: [
      "An agency delivering custom software solutions for big clients with portfolio of 100+ projects running concurrently",
      "I led teams building everything from MVPs to production systems",
      "Managed technical feasibility assessments and project estimation",
      "Architected scalable web applications and optimized development workflows",
      "Unblocked team members and removed technical barriers",
    ],
  },
  {
    company: "Invity.io",
    date: "2021 (contract)",
    position: "Product Manager",
    responsibilities: [
      "Product Manager at SatoshiLabs for Coinmap cryptocurrency location platform",
      "Did a comprehensive market research and competitive analysis",
      "Designed variants of business models and strategic roadmaps for C-level",
      "Made data-driven recommendation to C-level resulting in strategic pivot",
      "Identified critical risks and mitigation strategies",
      "Collaborated on marketing materials and cross-department alignment",
      "Recommended to close the product after thorough analysis of market conditions and internal capabilities",
    ],
  },
  {
    company: "Cinnamon",
    date: "2019 - 2021 (contract)",
    position: "Founding Product Engineer",
    responsibilities: [
      "Founding engineer at global social video platform with real-time crypto payouts",
      "From zero to production",
      "Architected complete monorepo structure with documentation and CI/CD workflows",
      "Designed and built UI library using atomic design system patterns",
      "Led feature development and major application initiatives",
      "Managed cross-team collaboration with external agencies",
      "Startup closed after 18 months due to market conditions exacerbated by the pandemic",
    ],
  },
  {
    company: "Mews Systems",
    date: "2019 (contract)",
    position: "Senior Frontend Engineer",
    responsibilities: [
      "Built features for B2C platform connecting hoteliers with customers",
      "Designed and developed instant messaging feature from prototype to production",
      "Contributed to shared UI library and platform packages",
      "Systematically addressed technical debt and improved codebase quality",
      "Contributed to code standards and best practices across the frontend team",
      "Mentored junior engineers and guided team knowledge sharing",
      "Engagement scope completed; messaging shipped and handed off",
    ],
  },
  {
    company: "Samba.ai",
    date: "2018 - 2019 (contract)",
    position: "Lead Frontend Engineer",
    responsibilities: [
      "Led frontend team of 2, architecting products from the ground up",
      "Designed frontend architecture, tech stack and development workflows for new products",
      "Hired and mentored engineering talent",
      "Bug fixing and feature implementation for two B2B products (React, Angular 1) plus internal systems",
      "Systematically refactored code and eliminated technical debt",
    ],
  },
  {
    company: "Spendee",
    date: "2016 - 2018 (contract)",
    position: "Lead Frontend Engineer",
    responsibilities: [
      "Led frontend team of 3, delivering complete web app redesign",
      "Advocated at C-level for and executed modern tech stack modernization",
      "Designed new repository with optimized development workflows",
      "Built responsive web application from scratch using latest technologies",
      "Hired talented engineers and kept team aligned and productive",
      "Designed tech stack, best practices and workflows",
    ],
  },
  {
    company: "STRV",
    date: "2015 - 2016 (contract)",
    position: "Frontend Engineer",
    responsibilities: [
      "Built multiple US startup products using cutting-edge technology",
      "Developed full-featured web applications (ride-sharing, investment platforms)",
      "Collaborated across diverse teams on high-velocity projects",
      "Established frontend code standards and best practices",
      "Early adopter of React, Redux, Webpack, CSS Modules",
    ],
  },
  {
    company: "IBM University Technology Center",
    date: "2012 - 2014",
    position: "BPM Developer & Consultant",
    responsibilities: [
      "Full-stack developer and designer for IBM BPM solutions",
      "Led UX, design, and frontend development for BPMN web application",
      "Created company visual identity and brand standards",
      "Designed marketing materials and enterprise presentations",
    ],
  },
];
