export default [
  {
    company: 'Exaforce',
    date: '2024 - 2025',
    position: 'Product Engineer',
    responsibilities: [
      'US-based AI-powered security startup (Series A, $75M raised)',
      'Developed core analytics features powering cloud security platform',
      'Collaborated directly with CEO on feature priorities and product direction',
      'Optimized SQL queries for real-time security intelligence and data processing',
      'Built customized frontend using Superset, React, TypeScript, Redux, Vite, TanStack Query/Table, Emotion CSS-in-JS',
      'Implemented YAML-driven dashboard configuration system',
    ],
  },
  {
    company: 'Vitus Labs',
    date: '2018 - 2024',
    position: 'Open Source Tooling Creator',
    responsibilities: [
      'Created open-source libraries for multiplatform UI design systems',
      'Developed tools that eliminate web/monorepo configuration overhead',
      'Helped teams build faster, more beautiful frontends with minimal setup',
      'Active contributor to the developer community',
    ],
  },
  {
    company: 'BOOTIQ',
    date: '2023',
    position: 'Tech Lead/Consultant',
    responsibilities: [
      'Partnered directly with clients on business-critical technical challenges',
      'Provided technical strategy and sales support for deal proposals',
      'Conducted deep technical analyses and architecture recommendations',
      'Designed scalable web application architectures and development workflows',
      'Resolved critical production issues for client projects',
      'Evaluated team capabilities and defined growth strategies',
    ],
  },
  {
    company: 'KINDRED.',
    date: '2021 - 2022',
    position: 'Engineering Team/Tech Lead',
    responsibilities: [
      'Led engineering team of 2, delivering high-impact client projects',
      'Managed technical feasibility assessments and project estimation',
      'Architected scalable web applications and optimized development workflows',
      'Unblocked team members and removed technical barriers',
      'Contributed to company processes and strategic vision',
    ],
  },
  {
    company: 'Invity.io',
    date: '2021',
    position: 'Product Manager',
    responsibilities: [
      'Product Manager at SatoshiLabs for Coinmap cryptocurrency location platform',
      'Conducted comprehensive market research and competitive analysis',
      'Developed business models and strategic roadmaps',
      'Made data-driven recommendation to C-level resulting in strategic pivot',
      'Identified critical risks and mitigation strategies',
      'Collaborated on marketing materials and cross-department alignment',
    ],
  },
  {
    company: 'Cinnamon',
    date: '2019 - 2021',
    position: 'Founding Product Engineer',
    responsibilities: [
      'Founding engineer at global social video platform with real-time crypto payouts',
      'Architected complete monorepo structure with documentation and CI/CD workflows',
      'Designed and built UI library using atomic design system patterns',
      'Led feature development and major application rewrites',
      'Managed cross-team collaboration with external agencies',
      'Participated in hackathon exploring innovative micro-payment solutions',
    ],
  },
  {
    company: 'Mews Systems',
    date: '2019',
    position: 'Frontend Engineer',
    responsibilities: [
      'Built features for B2C platform connecting hoteliers with customers',
      'Designed and developed instant messaging feature from prototype to production',
      'Contributed to shared UI library and platform packages',
      'Systematically addressed technical debt and improved codebase quality',
      'Established code standards and best practices documentation',
      'Mentored junior engineers and guided team knowledge sharing',
    ],
  },
  {
    company: 'Samba.ai',
    date: '2018 - 2019',
    position: 'Lead Frontend Engineer',
    responsibilities: [
      'Led frontend team of 2, architecting products from the ground up',
      'Designed scalable frontend architecture and development workflows',
      'Hired and mentored engineering talent',
      'Maintained two B2B products (React, Angular 1) plus internal systems',
      'Systematically refactored code and eliminated technical debt',
    ],
  },
  {
    company: 'Spendee',
    date: '2016 - 2018',
    position: 'Lead Frontend Engineer',
    responsibilities: [
      'Led frontend team of 3, delivering complete web app redesign',
      'Advocated for and executed modern tech stack modernization',
      'Designed new repository with optimized development workflows',
      'Built responsive web application from scratch using latest technologies',
      'Hired talented engineers and kept team aligned and productive',
      'Maintained cutting-edge tech stack and best practices',
    ],
  },
  {
    company: 'STRV',
    date: '2015 - 2016',
    position: 'Frontend Engineer',
    responsibilities: [
      'Built multiple US startup products using cutting-edge technology',
      'Developed full-featured web applications (ride-sharing, investment platforms)',
      'Collaborated across diverse teams on high-velocity projects',
      'Established frontend code standards and best practices',
      'Early adopter of React, Redux, webpack, CSS Modules',
    ],
  },
  {
    company: 'IBM University Technology Center',
    date: '2012 - 2014',
    position: 'BPM Developer, Consultant & Designer',
    responsibilities: [
      'Full-stack developer and designer for IBM BPM solutions',
      'Led UX, design, and frontend development for BPMN web application',
      'Created company visual identity and brand standards',
      'Designed marketing materials and enterprise presentations',
    ],
  },
]
