export default [
  {
    company: 'Exaforce',
    date: '2024 - 2025',
    position: 'Product Engineer',
    responsibilities: [
      'A US based fast paced AI powered security start up that raised $75 mio in Series A',
      'Analytical platform that dramatically simplifies cloud security and operations',
      'Direct communication with CEO about priorities and moving the company challenges forward',
      'Doing everything needed (well, startup)',
      'Tuning SQL queries to get the data that helps you stay secure',
      'Building customized frontend app using Superset, Typescript, React, MobX, Redux, Vite, TanStack Query, TanStack Table, react-intl, Emotion CSS-in-JS, monorepo',
      'Configuring dashboards via YAML structure',
      'And much more...',
    ],
  },
  {
    company: 'Vitus Labs',
    date: '2018 - 2024',
    position: 'Open Source Tooling Creator',
    responsibilities: [
      'Founded a side hobby open-source project I work on in my free time to give back to the community',
      'Turned into life couple of ideas to innovate and make frontend development faster and beautiful',
      'A set of libraries to design and develop fast multiplatform UI design systems',
      'Ready to use tools to eliminate configurations of web/monorepo setup',
    ],
  },
  {
    company: 'BOOTIQ',
    date: '2023',
    position: 'Tech Lead/Consultant',
    responsibilities: [
      'Direct communication with clients and facing their business challenges',
      'Business sales technical support',
      'Preparing deal proposals and technical presentations',
      'Deep technical project analyses',
      'Settle up web application architecture and managing development workflows',
      'Solving critical issues on client projects',
      'Team skill evaluation and defining career growth path',
    ],
  },
  {
    company: 'KINDRED.',
    date: '2021 - 2022',
    position: 'Engineering Team/Tech Lead',
    responsibilities: [
      'Managing couple of engineers',
      'Responsible for delivering client projects',
      'Regular calls with clients, discussing technical feasibility, tech complexity, time estimations etc.',
      'Unblocking people',
      'Designing web application architecture, managing development workflows',
      'Contribution to the company processes and vision',
    ],
  },
  {
    company: 'Invity.io',
    date: '2021',
    position: 'Product Manager',
    responsibilities: [
      'Part of SatoshiLabs, Product Manager of Coinmap',
      'A main mission was to find a great business model and settle up a vision',
      'In the end, I have made a hard decision and recommended to C-level to cut the project (or at least to postpone the realisation) due to shift of company priorities and higher business potential',
      'Made a deep analysis based on market research, consumer behavior, competitors etc.',
      'Prepared business plan(s) and defined expectations',
      'Analysed possible risks',
      'Helped designing marketing materials',
      'Organised weekly sync meeting within departments',
    ],
  },
  {
    company: 'Cinnamon',
    date: '2019 - 2021',
    position: 'Founding Product Engineer',
    responsibilities: [
      'A founding engineer in a fast paced start up that is not running anymore',
      'A global social video platform similar to TikTok with real-time crypto pay outs to content creators',
      'Designing a complete monorepo structure + documentation with related workflows',
      'Designed automation processes and solutions for CI/CD',
      'UI design process & developed UI library using atomic design system patterns',
      'Responsible for collaboration with colleagues from an external agency',
      'Built new features & rewriting an old app to a brand new web app',
      'Attended hackathon (a competition) focused on online micro payments',
      'And much much more...',
    ],
  },
  {
    company: 'Mews Systems',
    date: '2019',
    position: 'Frontend Engineer',
    responsibilities: [
      'Collaboration in a team working on a B2C product connecting hoteliers with their customers',
      'Worked on a prototyping and later on developing an instant messaging feature',
      'Contributed to UI library and other platform packages in monorepo',
      'Helped to catch up on technical debt',
      'Contributed to code styles & documentation',
      'Code reviews',
      'Supported new additions to our team and sharing knowledge (not only) with them',
      'Helped junior engineers to grow'
    ],
  },
  {
    company: 'Samba.ai',
    date: '2018 - 2019',
    position: 'Lead Frontend Engineer',
    responsibilities: [
      'Hiring and interviewing engineering candidates',
      ' Designing a complete frontend architecture for a new product from scratch',
      ' Setting up development workflows and best practices',
      'Led a team of 2 people',
      'Taking care of everything related to frontend',
      'Maintained two B2B products (one running on ReactJS, the other on Angular 1) + internal systems',
      'Fixing technical debt and coding anti-patterns, refactoring old code',
      'Defined an architecture for a new product development'
    ],
  },
  {
    company: 'Spendee',
    date: '2016 - 2018',
    position: 'Lead Frontend Engineer',
    responsibilities: [
      'Convinced the C-level management to start a new up to date episode of the web app and delivered',
      'Hiring and interviewing engineering candidates',
      'Led a team of 3 people',
      'Worked on quick prototypes of new UI designs together with designer',
      'Designed and setup a new repository with all the workflows',
      'Developed a new responsive web app from scratch',
      'Supported my team and kept them on track',
      'Kept the tech stack up-to-date on regularly basis'
    ],
  },
  {
    company: 'STRV',
    date: '2015 - 2016',
    position: 'Frontend Engineer',
    responsibilities: [
      'Building US startups in no time using top notch tech',
      'Built a startup web app similar to Uber or Bolt; or an investment platform',
      'Collaboration in different teams',
      'Contribution to company frontend code styles',
      'Early adoption of cutting edge tech like React, Redux, webpack, CSS Modules etc.'
    ],
  },
  {
    company: 'IBM University Technology Center',
    date: '2012 - 2014',
    position: 'BPM Developer, Consultant & Designer',
    responsibilities: [
      'IBM BPM - User Experience | Design | Development',
      'BPMN WebApp - User Experience | Webdesign | Front-end Development',
      'New company visual identity',
      'Designing posters, flayers, websites, presentations and documents'
    ],
  },
]
