import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { basename, dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')

const buildRegistry = (dir: string, outFile: string) => {
  const fullDir = join(root, dir)
  const files = readdirSync(fullDir).filter((f) => f.endsWith('.svg'))
  const entries = files.map((f) => {
    const name = basename(f, '.svg')
    const content = readFileSync(join(fullDir, f), 'utf8').trim()
    return [name, content] as const
  })
  const lines = [
    '// Auto-generated by scripts/build-svg-registries.ts — do not edit.',
    '',
    'export const svgs: Record<string, string> = {',
    ...entries.map(([n, c]) => `  ${JSON.stringify(n)}: ${JSON.stringify(c)},`),
    '}',
    '',
  ]
  writeFileSync(join(root, outFile), lines.join('\n'))
  // biome-ignore lint/suspicious/noConsole: build script
  console.log(`Wrote ${outFile} (${entries.length} svgs)`)
}

buildRegistry('src/assets/icons', 'src/assets/icons/index.ts')
buildRegistry('src/assets/logo', 'src/assets/logo/index.ts')
